# Generated by Django 5.0.1 on 2024-02-15 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign_up_and_log_in_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='daate_joined',
            new_name='date_joined',
        ),
    ]
